# Auto-generated by Vertumnus v0.1
# DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.
# Thin Python shim — re-exports bindings from the native module.

from ._core import (  # type: ignore
    Color,
    Counter,
    DataStore,
    first_and_last,
    flatten_options,
    intersect_sets,
    lookup_or_default,
    merge_maps,
    sum_list,
    unique_sorted,
    unique_words,
    unzip_pairs,
    validate_string,
    word_frequencies,
)

__version__ = "0.3.0"
