// Auto-generated by Vertumnus v0.3.0 — https://github.com/Zikithezikit/Vertumnus
// DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.

#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use pyo3::prelude::*;
use pyo3::exceptions::PyRuntimeError;
use ::string_utils as _crate;

/// Reverses a string.
///
/// # Examples
///
/// ```
/// assert_eq!(string_utils::reverse("hello"), "olleh");
/// ```
#[pyfunction]
pub fn reverse(s: &str) -> String {
    _crate::reverse(s)
}

/// Counts the number of words in a string.
#[pyfunction]
pub fn word_count(s: &str) -> usize {
    _crate::word_count(s)
}

/// Checks if a string is a palindrome.
///
/// Returns `true` if the string reads the same forwards and backwards
/// (ignoring case and whitespace).
#[pyfunction]
pub fn is_palindrome(s: &str) -> bool {
    _crate::is_palindrome(s)
}

/// Truncates a string to the given length, appending "..." if truncated.
#[pyfunction]
pub fn truncate(s: &str, max_len: usize) -> String {
    _crate::truncate(s, max_len)
}

/// A simple text processor that can transform strings.
#[pyclass]
pub struct TextProcessor {
    inner: _crate::TextProcessor,
}

#[pymethods]
impl TextProcessor {
    /// Getter for `prefix`
    #[getter(prefix)]
    fn prefix(&self) -> String {
        self.inner.prefix.clone()
    }

    /// Getter for `uppercase`
    #[getter(uppercase)]
    fn uppercase(&self) -> bool {
        self.inner.uppercase
    }

    /// Create a new `TextProcessor`.
    #[new]
    pub fn new(prefix: String, uppercase: bool) -> Self {
        TextProcessor { inner: _crate::TextProcessor::new(prefix, uppercase) }
    }

    /// Process a string by adding the prefix and optionally uppercasing.
    pub fn process(&self, input: &str) -> String {
        self.inner.process(input)
    }

    /// Returns a greeting message.
    pub fn greet(&self, name: &str) -> String {
        self.inner.greet(name)
    }

}

/// Status of a text processing operation.
#[pyclass(eq, eq_int)]
#[derive(Clone, PartialEq)]
pub enum ProcessStatus {
    Success,
    EmptyInput,
    TooLong,
}

impl From<ProcessStatus> for _crate::ProcessStatus {
    fn from(val: ProcessStatus) -> Self {
        match val {
            ProcessStatus::Success => _crate::ProcessStatus::Success,
            ProcessStatus::EmptyInput => _crate::ProcessStatus::EmptyInput,
            ProcessStatus::TooLong => _crate::ProcessStatus::TooLong,
        }
    }
}

impl From<_crate::ProcessStatus> for ProcessStatus {
    fn from(val: _crate::ProcessStatus) -> Self {
        match val {
            _crate::ProcessStatus::Success => ProcessStatus::Success,
            _crate::ProcessStatus::EmptyInput => ProcessStatus::EmptyInput,
            _crate::ProcessStatus::TooLong => ProcessStatus::TooLong,
            _ => panic!("Unknown variant of _crate::ProcessStatus")
        }
    }
}

#[pymethods]
impl ProcessStatus {
    /// Check if the status indicates success.
    pub fn is_ok(&self) -> bool {
        _crate::ProcessStatus::is_ok(&_crate::ProcessStatus::from(self.clone()))
    }

    /// Get a human-readable description.
    pub fn description(&self) -> &str {
        _crate::ProcessStatus::description(&_crate::ProcessStatus::from(self.clone()))
    }

}

/// Vertumnus-generated Python bindings for `string_utils` v0.2.0
#[pymodule]
fn _core(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.setattr("__doc__", "Reverses a string.")?;

    // --- Register functions ---
    m.add_function(wrap_pyfunction!(reverse, m)?)?;
    m.add_function(wrap_pyfunction!(word_count, m)?)?;
    m.add_function(wrap_pyfunction!(is_palindrome, m)?)?;
    m.add_function(wrap_pyfunction!(truncate, m)?)?;

    // --- Register classes ---
    m.add_class::<TextProcessor>()?;
    m.add_class::<ProcessStatus>()?;

    Ok(())
}