// Auto-generated by Vertumnus v0.3.0 — https://github.com/Zikithezikit/Vertumnus
// DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.

#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use pyo3::prelude::*;
use pyo3::exceptions::PyRuntimeError;
use ::simple_math as _crate;

/// Adds two 64-bit integers.
///
/// # Examples
///
/// ```
/// assert_eq!(simple_math::add(2, 3), 5);
/// ```
#[pyfunction]
pub fn add(a: i64, b: i64) -> i64 {
    _crate::add(a, b)
}

/// Divides two floating-point numbers.
///
/// Returns `None` if division by zero would occur.
#[pyfunction]
pub fn div(a: f64, b: f64) -> Option<f64> {
    _crate::div(a, b)
}

/// Computes the length of a vector.
#[pyfunction]
pub fn magnitude(x: f64, y: f64, z: f64) -> f64 {
    _crate::magnitude(x, y, z)
}

/// A 2D point with floating-point coordinates.
#[pyclass]
pub struct Point {
    inner: _crate::Point,
}

#[pymethods]
impl Point {
    /// Getter for `x`
    #[getter(x)]
    fn x(&self) -> f64 {
        self.inner.x
    }

    /// Getter for `y`
    #[getter(y)]
    fn y(&self) -> f64 {
        self.inner.y
    }

    /// Create a new `Point`.
    #[new]
    pub fn new(x: f64, y: f64) -> Self {
        Point { inner: _crate::Point::new(x, y) }
    }

    /// Compute the distance between two points.
    pub fn distance(&self, other: &Point) -> f64 {
        self.inner.distance(&other.inner)
    }

    /// Move the point by a delta.
    pub fn translate(&mut self, dx: f64, dy: f64) {
        self.inner.translate(dx, dy);
    }

}

/// Cardinal and intercardinal directions.
#[pyclass(eq, eq_int)]
#[derive(Clone, PartialEq)]
pub enum Direction {
    North,
    South,
    East,
    West,
    NorthEast,
    NorthWest,
    SouthEast,
    SouthWest,
}

impl From<Direction> for _crate::Direction {
    fn from(val: Direction) -> Self {
        match val {
            Direction::North => _crate::Direction::North,
            Direction::South => _crate::Direction::South,
            Direction::East => _crate::Direction::East,
            Direction::West => _crate::Direction::West,
            Direction::NorthEast => _crate::Direction::NorthEast,
            Direction::NorthWest => _crate::Direction::NorthWest,
            Direction::SouthEast => _crate::Direction::SouthEast,
            Direction::SouthWest => _crate::Direction::SouthWest,
        }
    }
}

impl From<_crate::Direction> for Direction {
    fn from(val: _crate::Direction) -> Self {
        match val {
            _crate::Direction::North => Direction::North,
            _crate::Direction::South => Direction::South,
            _crate::Direction::East => Direction::East,
            _crate::Direction::West => Direction::West,
            _crate::Direction::NorthEast => Direction::NorthEast,
            _crate::Direction::NorthWest => Direction::NorthWest,
            _crate::Direction::SouthEast => Direction::SouthEast,
            _crate::Direction::SouthWest => Direction::SouthWest,
            _ => panic!("Unknown variant of _crate::Direction")
        }
    }
}

#[pymethods]
impl Direction {
    /// Returns the direction as a (dx, dy) offset.
    pub fn offset(&self) -> (i32, i32) {
        _crate::Direction::offset(&_crate::Direction::from(self.clone()))
    }

}

// VERTUMNUS: manual binding required
// WARNING: Generic parameter 'T' cannot be resolved without monomorphization.
// WARNING: Field 'inner' has unsupported type — manual binding required
// WARNING: Struct 'Wrapper' has generic parameters — generated binding will not be generic.
#[allow(dead_code)]
pub struct Wrapper {
    _phantom: std::marker::PhantomData<Wrapper>,
}

/// A result type for fallible operations.
#[pyclass(eq, eq_int)]
#[derive(Clone, PartialEq)]
pub enum MathError {
    DivisionByZero,
    Overflow,
}

impl From<MathError> for _crate::MathError {
    fn from(val: MathError) -> Self {
        match val {
            MathError::DivisionByZero => _crate::MathError::DivisionByZero,
            MathError::Overflow => _crate::MathError::Overflow,
        }
    }
}

impl From<_crate::MathError> for MathError {
    fn from(val: _crate::MathError) -> Self {
        match val {
            _crate::MathError::DivisionByZero => MathError::DivisionByZero,
            _crate::MathError::Overflow => MathError::Overflow,
            _ => panic!("Unknown variant of _crate::MathError")
        }
    }
}

/// Performs integer division with error handling.
#[pyfunction]
pub fn safe_div(a: i64, b: i64) -> PyResult<i64> {
    _crate::safe_div(a, b).map_err(|e| PyRuntimeError::new_err(format!("{:?}", e)))
}

// VERTUMNUS: manual binding required
// WARNING: Reference with lifetime 'a' in '&'a str' — lifetime elided for Python binding.
// WARNING: Struct 'Ref' has lifetime parameters — not fully supported in v1. Generated binding will be a stub.
// WARNING: Struct 'Ref' has generic parameters — generated binding will not be generic.
#[allow(dead_code)]
pub struct Ref {
    _phantom: std::marker::PhantomData<Ref>,
}

/// Vertumnus-generated Python bindings for `simple_math` v0.1.0
#[pymodule]
fn _core(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.setattr("__doc__", "Adds two 64-bit integers.")?;

    // --- Register functions ---
    m.add_function(wrap_pyfunction!(add, m)?)?;
    m.add_function(wrap_pyfunction!(div, m)?)?;
    m.add_function(wrap_pyfunction!(magnitude, m)?)?;
    m.add_function(wrap_pyfunction!(safe_div, m)?)?;

    // --- Register classes ---
    m.add_class::<Point>()?;
    m.add_class::<Direction>()?;
    m.add_class::<MathError>()?;

    Ok(())
}