# Auto-generated by Vertumnus v0.1
# DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.
# Type stubs for `string_utils` v0.2.0

from typing import Any, overload

# Reverses a string.
# 
# # Examples
# 
# ```
# assert_eq!(string_utils::reverse("hello"), "olleh");
# ```
def reverse(s: str) -> str: ...

# Counts the number of words in a string.
def word_count(s: str) -> int: ...

# Checks if a string is a palindrome.
# 
# Returns `true` if the string reads the same forwards and backwards
# (ignoring case and whitespace).
def is_palindrome(s: str) -> bool: ...

# Truncates a string to the given length, appending "..." if truncated.
def truncate(s: str, max_len: int) -> str: ...

# A simple text processor that can transform strings.
class TextProcessor:
    prefix: str
    uppercase: bool

    # Create a new `TextProcessor`.
    def new(prefix: str, uppercase: bool) -> Self: ...

    # Process a string by adding the prefix and optionally uppercasing.
    def process(self, input: str) -> str: ...

    # Returns a greeting message.
    def greet(self, name: str) -> str: ...


from enum import IntEnum

# Status of a text processing operation.
class ProcessStatus(IntEnum):
    Success = ...
    EmptyInput = ...
    TooLong = ...

    # Check if the status indicates success.
    def is_ok(self) -> bool: ...

    # Get a human-readable description.
    def description(self) -> 'static str: ...


