# Auto-generated by Vertumnus v0.1
# DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.
# Type stubs for `simple_math` v0.1.0

from typing import Any, overload

# Adds two 64-bit integers.
# 
# # Examples
# 
# ```
# assert_eq!(simple_math::add(2, 3), 5);
# ```
def add(a: int, b: int) -> int: ...

# Divides two floating-point numbers.
# 
# Returns `None` if division by zero would occur.
def div(a: float, b: float) -> float | None: ...

# Computes the length of a vector.
def magnitude(x: float, y: float, z: float) -> float: ...

# Performs integer division with error handling.
def safe_div(a: int, b: int) -> int: ...

# A 2D point with floating-point coordinates.
class Point:
    x: float
    y: float

    # Create a new `Point`.
    def new(x: float, y: float) -> Self: ...

    # Compute the distance between two points.
    def distance(self, other: Point) -> float: ...

    # Move the point by a delta.
    def translate(self, dx: float, dy: float) -> None: ...


from enum import IntEnum

# Cardinal and intercardinal directions.
class Direction(IntEnum):
    North = ...
    South = ...
    East = ...
    West = ...
    NorthEast = ...
    NorthWest = ...
    SouthEast = ...
    SouthWest = ...

    # Returns the direction as a (dx, dy) offset.
    def offset(self) -> tuple[int, int]: ...


# A result type for fallible operations.
class MathError(IntEnum):
    DivisionByZero = ...
    Overflow = ...


