// Auto-generated by Vertumnus v0.3.0 — https://github.com/Zikithezikit/Vertumnus
// DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.

#![allow(unused_imports)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use pyo3::prelude::*;
use pyo3::exceptions::PyRuntimeError;
use ::data_structures as _crate;

/// Returns the sum of a list of integers.
#[pyfunction]
pub fn sum_list(values: Vec<i64>) -> i64 {
    _crate::sum_list(values)
}

/// Returns a sorted list of unique values.
#[pyfunction]
pub fn unique_sorted(values: Vec<i64>) -> Vec<i64> {
    _crate::unique_sorted(values)
}

/// Counts word frequencies in a string.
#[pyfunction]
pub fn word_frequencies(text: &str) -> std::collections::HashMap<String, usize> {
    _crate::word_frequencies(text)
}

/// Computes a set of unique words from a text.
#[pyfunction]
pub fn unique_words(text: &str) -> std::collections::HashSet<String> {
    _crate::unique_words(text)
}

/// Looks up a value in a map, returning a default if missing.
#[pyfunction]
pub fn lookup_or_default(map: std::collections::HashMap<String, i64>, key: String, default: i64) -> i64 {
    _crate::lookup_or_default(map, key, default)
}

/// Merges two maps, with the second map overwriting the first.
#[pyfunction]
pub fn merge_maps(a: std::collections::HashMap<String, i64>, b: std::collections::HashMap<String, i64>) -> std::collections::HashMap<String, i64> {
    _crate::merge_maps(a, b)
}

/// Finds the intersection of two sets.
#[pyfunction]
pub fn intersect_sets(a: std::collections::HashSet<i64>, b: std::collections::HashSet<i64>) -> Vec<i64> {
    _crate::intersect_sets(a, b)
}

/// Returns the first and last elements of a list, if non-empty.
#[pyfunction]
pub fn first_and_last(values: Vec<i64>) -> Option<(i64, i64)> {
    _crate::first_and_last(values)
}

/// Splits a tuple pair into two lists.
#[pyfunction]
pub fn unzip_pairs(pairs: Vec<(String, i64)>) -> (Vec<String>, Vec<i64>) {
    _crate::unzip_pairs(pairs)
}

/// Converts a list of options, filtering out None.
#[pyfunction]
pub fn flatten_options(values: Vec<Option<i64>>) -> Vec<i64> {
    _crate::flatten_options(values)
}

// VERTUMNUS: manual binding required
// WARNING: Enum 'ValidationError' has data-carrying variants — requires manual binding.
#[allow(dead_code)]
pub enum ValidationError {}

/// Validates that a string meets certain criteria.
#[pyfunction]
pub fn validate_string(s: &str, max_len: usize) -> PyResult<String> {
    _crate::validate_string(s, max_len).map_err(|e| PyRuntimeError::new_err(format!("{:?}", e)))
}

/// A container for a collection of named values.
#[pyclass]
pub struct DataStore {
    inner: _crate::DataStore,
}

#[pymethods]
impl DataStore {
    /// Getter for `name`
    #[getter(name)]
    fn name(&self) -> String {
        self.inner.name.clone()
    }

    /// Getter for `values`
    #[getter(values)]
    fn values(&self) -> Vec<i64> {
        self.inner.values.clone()
    }

    /// Getter for `entries`
    #[getter(entries)]
    fn entries(&self) -> std::collections::HashMap<String, f64> {
        self.inner.entries.clone()
    }

    /// Create a new DataStore.
    #[new]
    pub fn new(name: String) -> Self {
        DataStore { inner: _crate::DataStore::new(name) }
    }

    /// Add a value to the store.
    pub fn add_value(&mut self, val: i64) {
        self.inner.add_value(val);
    }

    /// Add a named entry.
    pub fn add_entry(&mut self, key: String, val: f64) {
        self.inner.add_entry(key, val);
    }

    /// Compute the sum of all values.
    pub fn total(&self) -> i64 {
        self.inner.total()
    }

    /// Returns the average of values, or None if empty.
    pub fn average(&self) -> Option<f64> {
        self.inner.average()
    }

    /// Merge another DataStore into this one.
    pub fn merge(&mut self, other: &DataStore) {
        self.inner.merge(&other.inner);
    }

}

/// A counter that can be incremented and queried.
#[pyclass]
pub struct Counter {
    inner: _crate::Counter,
}

#[pymethods]
impl Counter {
    /// Getter for `count`
    #[getter(count)]
    fn count(&self) -> i64 {
        self.inner.count
    }

    // VERTUMNUS: Field 'history' would conflict with PyO3's internal getter slot 'get_history'. Manual getter required.
    /// Create a new Counter starting at 0.
    #[new]
    pub fn new() -> Self {
        Counter { inner: _crate::Counter::new() }
    }

    /// Increment the counter by `amount`.
    pub fn increment(&mut self, amount: i64) -> i64 {
        self.inner.increment(amount)
    }

    /// Reset the counter to 0.
    pub fn reset(&mut self) {
        self.inner.reset();
    }

    /// Get the full history of count values.
    pub fn get_history(&self) -> Vec<i64> {
        self.inner.get_history()
    }

}

// VERTUMNUS: manual binding required
// WARNING: Enum 'OpStatus' has data-carrying variants — requires manual binding.
#[allow(dead_code)]
pub enum OpStatus {}

/// Simple value class — a C-like enum with no data variants.
#[pyclass(eq, eq_int)]
#[derive(Clone, PartialEq)]
pub enum Color {
    Red,
    Green,
    Blue,
    Yellow,
}

impl From<Color> for _crate::Color {
    fn from(val: Color) -> Self {
        match val {
            Color::Red => _crate::Color::Red,
            Color::Green => _crate::Color::Green,
            Color::Blue => _crate::Color::Blue,
            Color::Yellow => _crate::Color::Yellow,
        }
    }
}

impl From<_crate::Color> for Color {
    fn from(val: _crate::Color) -> Self {
        match val {
            _crate::Color::Red => Color::Red,
            _crate::Color::Green => Color::Green,
            _crate::Color::Blue => Color::Blue,
            _crate::Color::Yellow => Color::Yellow,
            _ => panic!("Unknown variant of _crate::Color")
        }
    }
}

#[pymethods]
impl Color {
    /// Convert the color to a hex-like numeric code.
    pub fn code(&self) -> i64 {
        _crate::Color::code(&_crate::Color::from(self.clone()))
    }

}

/// Vertumnus-generated Python bindings for `data_structures` v0.3.0
#[pymodule]
fn _core(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.setattr("__doc__", "Returns the sum of a list of integers.")?;

    // --- Register functions ---
    m.add_function(wrap_pyfunction!(sum_list, m)?)?;
    m.add_function(wrap_pyfunction!(unique_sorted, m)?)?;
    m.add_function(wrap_pyfunction!(word_frequencies, m)?)?;
    m.add_function(wrap_pyfunction!(unique_words, m)?)?;
    m.add_function(wrap_pyfunction!(lookup_or_default, m)?)?;
    m.add_function(wrap_pyfunction!(merge_maps, m)?)?;
    m.add_function(wrap_pyfunction!(intersect_sets, m)?)?;
    m.add_function(wrap_pyfunction!(first_and_last, m)?)?;
    m.add_function(wrap_pyfunction!(unzip_pairs, m)?)?;
    m.add_function(wrap_pyfunction!(flatten_options, m)?)?;
    m.add_function(wrap_pyfunction!(validate_string, m)?)?;

    // --- Register classes ---
    m.add_class::<DataStore>()?;
    m.add_class::<Counter>()?;
    m.add_class::<Color>()?;

    Ok(())
}