# Auto-generated by Vertumnus v0.1
# DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.
# Type stubs for `data_structures` v0.3.0

from typing import Any, overload

# Returns the sum of a list of integers.
def sum_list(values: list[int]) -> int: ...

# Returns a sorted list of unique values.
def unique_sorted(values: list[int]) -> list[int]: ...

# Counts word frequencies in a string.
def word_frequencies(text: str) -> std::collections::HashMap: ...

# Computes a set of unique words from a text.
def unique_words(text: str) -> std::collections::HashSet: ...

# Looks up a value in a map, returning a default if missing.
def lookup_or_default(map: std::collections::HashMap, key: str, default: int) -> int: ...

# Merges two maps, with the second map overwriting the first.
def merge_maps(a: std::collections::HashMap, b: std::collections::HashMap) -> std::collections::HashMap: ...

# Finds the intersection of two sets.
def intersect_sets(a: std::collections::HashSet, b: std::collections::HashSet) -> list[int]: ...

# Returns the first and last elements of a list, if non-empty.
def first_and_last(values: list[int]) -> tuple[int, int] | None: ...

# Splits a tuple pair into two lists.
def unzip_pairs(pairs: list[tuple[str, int]]) -> tuple[list[str], list[int]]: ...

# Converts a list of options, filtering out None.
def flatten_options(values: list[int | None]) -> list[int]: ...

# Validates that a string meets certain criteria.
def validate_string(s: str, max_len: int) -> str: ...

# A container for a collection of named values.
class DataStore:
    name: str
    values: list[int]
    entries: std::collections::HashMap

    # Create a new DataStore.
    def new(name: str) -> Self: ...

    # Add a value to the store.
    def add_value(self, val: int) -> None: ...

    # Add a named entry.
    def add_entry(self, key: str, val: float) -> None: ...

    # Compute the sum of all values.
    def total(self) -> int: ...

    # Returns the average of values, or None if empty.
    def average(self) -> float | None: ...

    # Merge another DataStore into this one.
    def merge(self, other: DataStore) -> None: ...


# A counter that can be incremented and queried.
class Counter:
    count: int
    history: list[int]

    # Create a new Counter starting at 0.
    def new() -> Self: ...

    # Increment the counter by `amount`.
    def increment(self, amount: int) -> int: ...

    # Reset the counter to 0.
    def reset(self) -> None: ...

    # Get the full history of count values.
    def get_history(self) -> list[int]: ...


from enum import IntEnum

# Simple value class — a C-like enum with no data variants.
class Color(IntEnum):
    Red = ...
    Green = ...
    Blue = ...
    Yellow = ...

    # Convert the color to a hex-like numeric code.
    def code(self) -> int: ...


