//! Python stub generation (.pyi and __init__.py) for Vertumnus bindings.
//!
//! Generates:
//! - `<package_name>.pyi` — Type stub file for IDE/type-checker support
//! - `python/<package_name>/__init__.py` — Thin re-export shim

use std::collections::HashMap;

use vertumnus_inspector::ir::{FieldVisibility, FunctionItem, IrItem, StructField};
use vertumnus_mapper::annotated_ir::{AnnotatedIr, AnnotatedItem, PyO3Strategy};



/// Generated Python stub output.
#[derive(Debug, Clone)]
pub struct GeneratedStubs {
    /// The `.pyi` file content
    pub pyi: String,
    /// The `__init__.py` file content
    pub init_py: String,
}

/// Generate the `.pyi` type stub file.
pub fn generate_pyi(
    annotated: &AnnotatedIr,
    _package_name: &str,
    methods_by_type: &HashMap<String, Vec<(FunctionItem, PyO3Strategy)>>,
) -> String {
    let mut pyi = String::new();

    // Header
    pyi.push_str("# Auto-generated by Vertumnus v0.1\n");
    pyi.push_str("# DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.\n");
    pyi.push_str(&format!(
        "# Type stubs for `{}` v{}\n\n",
        annotated.crate_name, annotated.crate_version
    ));

    // Imports
    pyi.push_str("from typing import Any, overload\n\n");

    // Separate items by kind so we output in order: functions → classes → enums
    let items: Vec<&AnnotatedItem> = annotated.items.iter().collect();
    let (functions, structs, enums, traits, _impls) = partition_map_by_kind(&items);

    // Free functions
    for item in &functions {
        if !is_exportable(&item.mapping.pyo3_strategy) {
            continue;
        }
        if let IrItem::Function(ref func) = item.original {
            pyi.push_str(&generate_function_stub(func, item));
        }
    }

    // Structs
    for item in &structs {
        if !is_exportable(&item.mapping.pyo3_strategy) {
            continue;
        }
        if let IrItem::Struct(ref s) = item.original {
            let methods = methods_by_type
                .get(&s.name)
                .map(|v| v.as_slice())
                .unwrap_or(&[]);
            pyi.push_str(&generate_struct_stub(s, methods, item));
        }
    }

    // Enums
    let has_c_like_enum = enums.iter().any(|item| {
        is_exportable(&item.mapping.pyo3_strategy)
            && matches!(&item.original, IrItem::Enum(e) if e.variants.iter().all(|v| v.fields.is_empty()))
    });
    if has_c_like_enum {
        pyi.push_str("from enum import IntEnum\n\n");
    }

    for item in &enums {
        if !is_exportable(&item.mapping.pyo3_strategy) {
            continue;
        }
        if let IrItem::Enum(ref e) = item.original {
            let methods = methods_by_type
                .get(&e.name)
                .map(|v| v.as_slice())
                .unwrap_or(&[]);
            pyi.push_str(&generate_enum_stub(e, methods, item));
        }
    }

    // Traits (informational)
    for item in &traits {
        pyi.push_str(&format!("# Trait '{}' — limited binding support\n\n", item.original.name()));
    }

    pyi
}

/// Generate the `__init__.py` re-export shim.
pub fn generate_init_py(annotated: &AnnotatedIr, package_name: &str) -> String {
    let mut init = String::new();

    init.push_str("# Auto-generated by Vertumnus v0.1\n");
    init.push_str("# DO NOT EDIT MANUALLY. Changes will be overwritten on re-generation.\n");
    init.push_str("# Thin Python shim — re-exports bindings from the native module.\n\n");

    init.push_str(&format!(
        "from .{} import (  # type: ignore\n",
        package_name
    ));

    // Collect all exportable names
    let mut names = Vec::new();
    for item in &annotated.items {
        match &item.original {
            IrItem::Function(f) => {
                if is_exportable(&item.mapping.pyo3_strategy) {
                    names.push(f.name.clone());
                }
            }
            IrItem::Struct(s) => {
                if is_exportable(&item.mapping.pyo3_strategy) {
                    names.push(s.name.clone());
                }
            }
            IrItem::Enum(e) => {
                if is_exportable(&item.mapping.pyo3_strategy) {
                    names.push(e.name.clone());
                }
            }
            _ => {}
        }
    }

    names.sort();
    for name in &names {
        init.push_str(&format!("    {},\n", name));
    }

    init.push_str(")\n\n");

    // Add a version attribute
    init.push_str(&format!(
        "__version__ = \"{}\"\n",
        annotated.crate_version
    ));

    init
}

/// Check if an item is exportable (not ManualStub-only).
fn is_exportable(strategy: &PyO3Strategy) -> bool {
    !matches!(strategy, PyO3Strategy::ManualStub)
}

// ---------------------------------------------------------------------------
// Per-type stub generators
// ---------------------------------------------------------------------------

/// Generate a Python stub for a free function.
fn generate_function_stub(func: &FunctionItem, item: &AnnotatedItem) -> String {
    let mut stub = String::new();

    // Doc comment
    if !func.doc.is_empty() {
        for line in func.doc.lines() {
            stub.push_str(&format!("# {}\n", line));
        }
    }

    // Manual stub warning
    if item.mapping.pyo3_strategy == PyO3Strategy::ManualStub {
        stub.push_str("# VERTUMNUS: manual binding required\n");
        for w in &item.mapping.warnings {
            stub.push_str(&format!("# WARNING: {}\n", w.message));
        }
        stub.push_str(&format!(
            "def {}(*args: Any, **kwargs: Any) -> Any: ...\n\n",
            func.name
        ));
        return stub;
    }

    // Async warning
    if func.is_async {
        stub.push_str("# NOTE: This function is async — use with an async runtime.\n");
        stub.push_str(&format!(
            "def {}(*args: Any, **kwargs: Any) -> Any: ...\n\n",
            func.name
        ));
        return stub;
    }

    // Build parameter list
    let params: Vec<String> = func
        .inputs
        .iter()
        .filter(|p| p.name != "self")
        .map(|p| {
            let py_type = ir_type_to_python_type(&p.type_str);
            format!("{}: {}", p.name, py_type)
        })
        .collect();

    // Build return type
    let return_type = if func.output.type_str == "()" {
        "None".to_string()
    } else if item.mapping.pyo3_strategy == PyO3Strategy::MapErr {
        // Result<T, E> — the return type is T (Err raises exception)
        let mapped = ir_type_to_python_type(&func.output.type_str);
        if mapped.starts_with("Result[") {
            // Extract T from Result[T, E]
            extract_python_result_ok(&mapped).unwrap_or(mapped)
        } else {
            mapped
        }
    } else {
        ir_type_to_python_type(&func.output.type_str)
    };

    stub.push_str(&format!(
        "def {}({}) -> {}: ...\n\n",
        func.name,
        params.join(", "),
        return_type
    ));

    stub
}

/// Generate a Python stub for a struct.
fn generate_struct_stub(
    s: &vertumnus_inspector::ir::StructItem,
    methods: &[(FunctionItem, PyO3Strategy)],
    item: &AnnotatedItem,
) -> String {
    let mut stub = String::new();

    // Doc comment
    if !s.doc.is_empty() {
        for line in s.doc.lines() {
            stub.push_str(&format!("# {}\n", line));
        }
    }

    // Manual stub warning
    if item.mapping.pyo3_strategy == PyO3Strategy::ManualStub {
        stub.push_str("# VERTUMNUS: manual binding required\n");
        for w in &item.mapping.warnings {
            stub.push_str(&format!("# WARNING: {}\n", w.message));
        }
        stub.push_str(&format!("class {}: ...\n\n", s.name));
        return stub;
    }

    stub.push_str(&format!("class {}:\n", s.name));

    // Public fields as annotations
    let public_fields: Vec<&StructField> = s
        .fields
        .iter()
        .filter(|f| f.visibility == FieldVisibility::Public)
        .collect();

    for field in &public_fields {
        let py_type = ir_type_to_python_type(&field.type_str);
        stub.push_str(&format!("    {}: {}\n", field.name, py_type));
    }

    if !public_fields.is_empty() {
        stub.push('\n');
    }

    // Methods
    for (method, strategy) in methods {
        let method_stub = generate_method_stub(method, strategy);
        for line in method_stub.lines() {
            stub.push_str("    ");
            stub.push_str(line);
            stub.push('\n');
        }
        stub.push('\n');
    }

    // If there are no public fields and no methods, add a placeholder
    if public_fields.is_empty() && methods.is_empty() {
        stub.push_str("    pass\n");
    }

    stub.push('\n');
    stub
}

/// Generate a Python stub for an enum.
fn generate_enum_stub(
    e: &vertumnus_inspector::ir::EnumItem,
    methods: &[(FunctionItem, PyO3Strategy)],
    item: &AnnotatedItem,
) -> String {
    let mut stub = String::new();

    // Doc comment
    if !e.doc.is_empty() {
        for line in e.doc.lines() {
            stub.push_str(&format!("# {}\n", line));
        }
    }

    // Manual stub warning
    if item.mapping.pyo3_strategy == PyO3Strategy::ManualStub {
        stub.push_str("# VERTUMNUS: manual binding required\n");
        for w in &item.mapping.warnings {
            stub.push_str(&format!("# WARNING: {}\n", w.message));
        }
        stub.push_str(&format!("class {}: ...\n\n", e.name));
        return stub;
    }

    let is_c_like = e.variants.iter().all(|v| v.fields.is_empty());

    if is_c_like {
        stub.push_str(&format!("class {}(IntEnum):\n", e.name));

        for variant in &e.variants {
            stub.push_str(&format!("    {} = ...\n", variant.name));
        }
    } else {
        stub.push_str(&format!("class {}:\n", e.name));

        for variant in &e.variants {
            if variant.fields.is_empty() {
                stub.push_str(&format!("    {}: \"{}\" = ...\n", variant.name, variant.name));
            } else {
                stub.push_str(&format!("    # {}: data variant\n", variant.name));
            }
        }
    }

    stub.push('\n');

    // Methods
    for (method, strategy) in methods {
        let method_stub = generate_method_stub(method, strategy);
        for line in method_stub.lines() {
            stub.push_str("    ");
            stub.push_str(line);
            stub.push('\n');
        }
        stub.push('\n');
    }

    stub.push('\n');
    stub
}

/// Generate a Python stub for a method.
fn generate_method_stub(method: &FunctionItem, strategy: &PyO3Strategy) -> String {
    let mut stub = String::new();

    // Doc comment
    if !method.doc.is_empty() {
        for line in method.doc.lines() {
            stub.push_str(&format!("# {}\n", line));
        }
    }

    if *strategy == PyO3Strategy::ManualStub {
        stub.push_str("# VERTUMNUS: manual binding required\n");
        stub.push_str(&format!(
            "def {}(self, *args: Any, **kwargs: Any) -> Any: ...\n",
            method.name
        ));
        return stub;
    }

    // Determine if this is a static method (no self)
    let has_self = method.inputs.first().map(|p| p.name.as_str()) == Some("self");

    // Build parameter list
    let mut params = Vec::new();
    if has_self {
        params.push("self".to_string());
    }
    for p in method.inputs.iter().filter(|p| p.name != "self") {
        let py_type = ir_type_to_python_type(&p.type_str);
        params.push(format!("{}: {}", p.name, py_type));
    }

    // Build return type
    let return_type = if method.output.type_str == "()" {
        "None".to_string()
    } else if *strategy == PyO3Strategy::MapErr {
        let mapped = ir_type_to_python_type(&method.output.type_str);
        if mapped.starts_with("Result[") {
            extract_python_result_ok(&mapped).unwrap_or(mapped)
        } else {
            mapped
        }
    } else if method.output.type_str == "Self" {
        "Self".to_string()
    } else {
        ir_type_to_python_type(&method.output.type_str)
    };

    stub.push_str(&format!(
        "def {}({}) -> {}: ...\n",
        method.name,
        params.join(", "),
        return_type
    ));

    stub
}

// ---------------------------------------------------------------------------
// Type string to Python type conversion
// ---------------------------------------------------------------------------

/// Convert an IR type string to a Python type annotation string.
///
/// This is used for `.pyi` stub generation.
fn ir_type_to_python_type(type_str: &str) -> String {
    let s = type_str.trim();

    match s {
        // Primitives
        "i8" | "i16" | "i32" | "i64" | "i128" | "isize"
        | "u8" | "u16" | "u32" | "u64" | "u128" | "usize" => "int".to_string(),
        "f32" | "f64" => "float".to_string(),
        "bool" => "bool".to_string(),
        "char" => "str".to_string(),
        "str" | "&str" => "str".to_string(),

        // Unit
        "()" => "None".to_string(),
        "!" => "typing.NoReturn".to_string(),

        // String
        "String" => "str".to_string(),

        // Self type
        "Self" => "Self".to_string(),

        // Reference types (strip the reference)
        _ if s.starts_with("&mut ") => {
            ir_type_to_python_type(&s[5..].trim())
        }
        _ if s.starts_with('&') => {
            ir_type_to_python_type(&s[1..].trim())
        }

        // Vec<T>
        _ if s.starts_with("Vec<") && s.ends_with('>') => {
            let inner = &s[4..s.len() - 1];
            format!("list[{}]", ir_type_to_python_type(inner))
        }

        // Option<T>
        _ if s.starts_with("Option<") && s.ends_with('>') && s.len() > 7 => {
            let inner = &s[7..s.len() - 1];
            let inner_py = ir_type_to_python_type(inner);
            if inner_py == "None" {
                "None".to_string()
            } else {
                format!("{} | None", inner_py)
            }
        }

        // Result<T, E>
        _ if s.starts_with("Result<") && s.ends_with('>') => {
            // Keep as Result<T, E> in stub — Python doesn't have native Result
            let inner = &s[7..s.len() - 1];
            // Split on first comma at top level for type args
            let parts = split_python_type_args(inner);
            if parts.len() >= 2 {
                format!(
                    "{}",
                    ir_type_to_python_type(parts[0].trim())
                )
            } else {
                "Any".to_string()
            }
        }

        // HashMap<K,V>
        _ if s.starts_with("HashMap<") && s.ends_with('>') => {
            let inner = &s[8..s.len() - 1];
            let parts = split_python_type_args(inner);
            if parts.len() >= 2 {
                format!(
                    "dict[{}, {}]",
                    ir_type_to_python_type(parts[0].trim()),
                    ir_type_to_python_type(parts[1].trim())
                )
            } else {
                "dict[Any, Any]".to_string()
            }
        }

        // HashSet<T>
        _ if s.starts_with("HashSet<") && s.ends_with('>') => {
            let inner = &s[8..s.len() - 1];
            format!("set[{}]", ir_type_to_python_type(inner))
        }

        // Box<T>
        _ if s.starts_with("Box<") && s.ends_with('>') => {
            let inner = &s[4..s.len() - 1];
            ir_type_to_python_type(inner)
        }

        // Tuple types
        _ if s.starts_with('(') && s.ends_with(')') => {
            let inner = &s[1..s.len() - 1];
            if inner.trim().is_empty() {
                "tuple[()]".to_string()
            } else {
                let parts: Vec<&str> = split_python_type_args(inner);
                let mapped: Vec<String> = parts
                    .iter()
                    .map(|p| ir_type_to_python_type(p.trim()))
                    .collect();
                if mapped.len() == 1 {
                    format!("tuple[{}]", mapped[0])
                } else {
                    format!("tuple[{}]", mapped.join(", "))
                }
            }
        }

        // dyn Trait
        _ if s.starts_with("dyn ") => "Any".to_string(),

        // impl Trait
        _ if s.starts_with("impl ") => "Any".to_string(),

        // Slice/array
        _ if s.starts_with('[') && s.ends_with(']') => {
            let inner = &s[1..s.len() - 1];
            if let Some(semi_pos) = inner.rfind("; ") {
                let elem = &inner[..semi_pos].trim();
                format!("list[{}]", ir_type_to_python_type(elem))
            } else if inner.trim().is_empty() {
                "list[Any]".to_string()
            } else {
                format!("list[{}]", ir_type_to_python_type(inner.trim()))
            }
        }

        // Generic named types
        _ if s.contains('<') && s.ends_with('>') => {
            // Try to parse as a named generic
            let angle_start = s.find('<').unwrap();
            let base = &s[..angle_start];
            base.to_string()
        }

        // Fallback: treat as a named type (struct/enum)
        _ => s.to_string(),
    }
}

/// Split type arguments at top-level commas for Python types.
fn split_python_type_args(s: &str) -> Vec<&str> {
    let mut args = Vec::new();
    let mut depth_angle = 0u32;
    let mut depth_paren = 0u32;
    let mut depth_bracket = 0u32;
    let mut start = 0usize;

    for (i, c) in s.char_indices() {
        match c {
            '<' => depth_angle += 1,
            '>' => depth_angle = depth_angle.saturating_sub(1),
            '(' => depth_paren += 1,
            ')' => depth_paren = depth_paren.saturating_sub(1),
            '[' => depth_bracket += 1,
            ']' => depth_bracket = depth_bracket.saturating_sub(1),
            ',' if depth_angle == 0 && depth_paren == 0 && depth_bracket == 0 => {
                args.push(&s[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }

    if start < s.len() {
        args.push(&s[start..]);
    }

    args
}

/// Extract Ok type from a Python-style `Result[T, E]` string.
fn extract_python_result_ok(type_str: &str) -> Option<String> {
    if type_str.starts_with("Result[") {
        let inner = &type_str[7..type_str.len() - 1];
        split_python_type_args(inner).first().map(|s| s.trim().to_string())
    } else {
        None
    }
}

// ---------------------------------------------------------------------------
// Free function for partitioning items by kind
// ---------------------------------------------------------------------------

/// Partition a slice of annotated items by their IR item kind.
fn partition_map_by_kind<'a>(
    items: &'a [&'a AnnotatedItem],
) -> (
    Vec<&'a AnnotatedItem>,
    Vec<&'a AnnotatedItem>,
    Vec<&'a AnnotatedItem>,
    Vec<&'a AnnotatedItem>,
    Vec<&'a AnnotatedItem>,
) {
    let mut functions = Vec::new();
    let mut structs = Vec::new();
    let mut enums = Vec::new();
    let mut traits = Vec::new();
    let mut impls = Vec::new();

    for item in items {
        match &item.original {
            IrItem::Function(_) => functions.push(*item),
            IrItem::Struct(_) => structs.push(*item),
            IrItem::Enum(_) => enums.push(*item),
            IrItem::Trait(_) => traits.push(*item),
            IrItem::Impl(_) => impls.push(*item),
        }
    }

    (functions, structs, enums, traits, impls)
}

#[cfg(test)]
mod tests {
    use super::*;
    use vertumnus_inspector::ir::{
        EnumItem, EnumVariant, FieldVisibility, FunctionItem, FunctionParameter,
        IntermediateRepresentation, IrItem, IrItemKind, IrType, StructField, StructItem,
    };
    use vertumnus_mapper::annotated_ir::{AnnotatedIr, PyO3Strategy};
    use vertumnus_mapper::map_ir;

    fn make_test_annotated() -> AnnotatedIr {
        let ir = IntermediateRepresentation {
            vertumnus_ir_version: "0.1".to_string(),
            crate_name: "simple_math".to_string(),
            crate_version: "0.1.0".to_string(),
            items: vec![
                IrItem::Function(FunctionItem {
                    kind: IrItemKind::Function,
                    name: "add".to_string(),
                    doc: "Adds two integers.".to_string(),
                    inputs: vec![
                        FunctionParameter { name: "a".to_string(), type_str: "i64".to_string() },
                        FunctionParameter { name: "b".to_string(), type_str: "i64".to_string() },
                    ],
                    output: IrType { type_str: "i64".to_string() },
                    is_unsafe: false,
                    is_async: false,
                    has_generics: false,
                    visibility: "public".to_string(),
                }),
                IrItem::Struct(StructItem {
                    kind: IrItemKind::Struct,
                    name: "Point".to_string(),
                    doc: "A 2D point.".to_string(),
                    fields: vec![
                        StructField { name: "x".to_string(), type_str: "f64".to_string(), visibility: FieldVisibility::Public },
                        StructField { name: "y".to_string(), type_str: "f64".to_string(), visibility: FieldVisibility::Public },
                    ],
                    methods: vec![],
                    has_lifetimes: false,
                    has_generics: false,
                }),
                IrItem::Enum(EnumItem {
                    kind: IrItemKind::Enum,
                    name: "Direction".to_string(),
                    doc: "Cardinal directions.".to_string(),
                    variants: vec![
                        EnumVariant { name: "North".to_string(), fields: vec![], discriminant: None },
                        EnumVariant { name: "South".to_string(), fields: vec![], discriminant: None },
                    ],
                    methods: vec![],
                    has_lifetimes: false,
                    has_generics: false,
                }),
            ],
        };
        map_ir(&ir).unwrap()
    }

    #[test]
    fn test_generate_function_stub() {
        let annotated = make_test_annotated();
        let item = &annotated.items[0];
        if let IrItem::Function(func) = &item.original {
            let stub = generate_function_stub(func, item);
            assert!(stub.contains("def add("));
            assert!(stub.contains("a: int"));
            assert!(stub.contains("b: int"));
            assert!(stub.contains("-> int"));
            assert!(stub.contains("..."));
        } else {
            panic!("Expected function item");
        }
    }

    #[test]
    fn test_generate_struct_stub() {
        let annotated = make_test_annotated();
        let item = &annotated.items[1];
        if let IrItem::Struct(ref s) = item.original {
            let stub = generate_struct_stub(s, &[], item);
            assert!(stub.contains("class Point:"));
            assert!(stub.contains("x: float"));
            assert!(stub.contains("y: float"));
        } else {
            panic!("Expected struct item");
        }
    }

    #[test]
    fn test_generate_enum_stub() {
        let annotated = make_test_annotated();
        let item = &annotated.items[2];
        if let IrItem::Enum(ref e) = item.original {
            let stub = generate_enum_stub(e, &[], item);
            assert!(stub.contains("class Direction("));
            assert!(stub.contains("North"));
            assert!(stub.contains("South"));
        } else {
            panic!("Expected enum item");
        }
    }

    #[test]
    fn test_generate_init_py() {
        let annotated = make_test_annotated();
        let init = generate_init_py(&annotated, "simple_math");
        assert!(init.contains("from .simple_math import ("));
        assert!(init.contains("add"));
        assert!(init.contains("Point"));
        assert!(init.contains("Direction"));
        assert!(init.contains("__version__"));
    }

    #[test]
    fn test_ir_type_to_python_type() {
        assert_eq!(ir_type_to_python_type("i32"), "int");
        assert_eq!(ir_type_to_python_type("f64"), "float");
        assert_eq!(ir_type_to_python_type("bool"), "bool");
        assert_eq!(ir_type_to_python_type("String"), "str");
        assert_eq!(ir_type_to_python_type("&str"), "str");
        assert_eq!(ir_type_to_python_type("()"), "None");
        assert_eq!(ir_type_to_python_type("Vec<f64>"), "list[float]");
        assert_eq!(ir_type_to_python_type("Option<i32>"), "int | None");
        assert_eq!(ir_type_to_python_type("HashMap<String, i64>"), "dict[str, int]");
        assert_eq!(ir_type_to_python_type("HashSet<String>"), "set[str]");
        assert_eq!(ir_type_to_python_type("(i32, f64)"), "tuple[int, float]");
        assert_eq!(ir_type_to_python_type("&Point"), "Point");
        assert_eq!(ir_type_to_python_type("dyn Display"), "Any");
    }

    #[test]
    fn test_partition_map_by_kind() {
        let annotated = make_test_annotated();
        let items: Vec<&AnnotatedItem> = annotated.items.iter().collect();
        let (funcs, structs, enums, traits, impls) = partition_map_by_kind(&items);
        assert_eq!(funcs.len(), 1);
        assert_eq!(structs.len(), 1);
        assert_eq!(enums.len(), 1);
        assert_eq!(traits.len(), 0);
        assert_eq!(impls.len(), 0);
    }

    #[test]
    fn test_is_exportable() {
        assert!(is_exportable(&PyO3Strategy::PyFunction));
        assert!(is_exportable(&PyO3Strategy::PyClass));
        assert!(is_exportable(&PyO3Strategy::PyEnum));
        assert!(!is_exportable(&PyO3Strategy::ManualStub));
    }
}
